[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"

[project]
name = "girder-multi-part-zip"
dynamic = ["version"]
description = "Girder plugin to concatenate and extract multi-part zip files"
readme = "README.md"
license = {text = "Apache 2.0"}
authors = [
    {name = "Josselin Duchateau"},
]
keywords = ["girder", "zip", "multipart", "extraction"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "girder>=3.0.0",
    "girder-jobs>=3.0.0",
    "requests",
]

[project.urls]
Homepage = "https://github.com/LIRYC-IHU/girder-oidc"
