services:
  girder:
    build: .
    container_name: girder-kitware
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_URL: https://keycloak.ihu-liryc.fr/
      KEYCLOAK_PUBLIC_URL: https://keycloak.ihu-liryc.fr/
    volumes:
      - ./logs:/root/.girder/logs
      - girder-assetstore:/var/girder/assetstore
    networks:
      - girder-network
      - girder-uploader
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    command: -d mongodb://mongo:27017/girder --host 0.0.0.0
    

  mongo:
    image: mongo:5.0
    container_name: girder-mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: girder
    networks:
      - girder-network
    restart: unless-stopped


volumes:
  girder-assetstore:
  mongo-data:

networks:
  girder-network:
    driver: bridge
    
  girder-uploader:
    external: true